<a id=0></a>  
# 1. Numpy ndarrayを理解する
### ※ Numpy : ”Numerical Python”、数値計算・配列計算を高速で実行できるパッケージ

---
### [1.Python ListとNumpy ndarray ](#1)
### [2.Numpyの関数で連番、等差数列を作成](#2)
### [3.Randomモジュールによる乱数Arrayの作成と次元の変換](#3)
### [4.Numpy ndarrayの次元、形状、サイズ](#4)
### [5.Numpy ndarrayの演算例](#5)
---

Numpyをnpというエイリアス（別名）でインポートする  

In [1]:
import numpy as np

---
<a id=1></a>
[Topへ](#0)

---
## 1.Python ListとNumpy ndarray      

* ListとNumpy ndarrayを作成
* 型（タイプ）を確認  
* Numpy ndarrayのデータタイプ（Numpy ndarrayではすべての要素のデータタイプが統一される）
* Numpy ndarrayの演算例
* Numpy ndarrayの最大値、最小値、平均、合計
* Numpy ndarrayは要素の形状を一定に
* Numpy ndarrayのデータタイプ変換
---

List と ndarrayを作成

In [4]:
arry1 = [1, 2, 3]
arry2 = [4,5,6]
arry1



[1, 2, 3]

In [6]:
np_array1 = np.array(arry1)
np_array2 = np.array(arry2)
np_array1

array([1, 2, 3])

型（タイプ）を確認  
※ ndarray : n dimentional array（多次元配列）

In [7]:
print(type(arry1))
print(type(np_array1))

<class 'list'>
<class 'numpy.ndarray'>


In [8]:
np_array1.dtype

dtype('int64')

In [10]:
# arry1.dtype

NumpyArrayの演算例

In [12]:
np_array1 * 2

[1, 2, 3, 1, 2, 3]

In [13]:
arry1 * 2

[1, 2, 3, 1, 2, 3]

In [14]:
np_array1 + np_array2

array([5, 7, 9])

In [15]:
arry1 + arry2

[1, 2, 3, 4, 5, 6]

In [16]:
np_array1 * np_array2

array([ 4, 10, 18])

In [18]:
# arry1 * arry2


Numpy ndarrayの最大値、最小値、平均、合計、分散（全要素に対する）

In [21]:
np_array1.max()

3

In [23]:
np_array1.min()

1

In [24]:
np_array1.mean()

2.0

In [25]:
np_array1.var()

0.6666666666666666

ファンシーインデックス

In [26]:
array3 = [[0, 100], [200, 300]]
np_array3 = np.array((array3))

In [29]:
np_array3.shape

(2, 2)

In [30]:
array3[0][0]

0

Numpy ndarrayは各次元の要素の形状を一定に

In [32]:
array4 = [0 , [100, 200], [300, 400, 500]]
# np_array4 = np.array(array4)

Numpy ndarrayのデータタイプ変換

In [34]:
array6 = [[0, 1, 2.0], [3, 4,5]]
np_array6 = np.array(array6)
np_array6

array([[0., 1., 2.],
       [3., 4., 5.]])

In [36]:
np_array6.dtype

dtype('float64')

In [39]:
np_array6.astype(int)
np_array6.dtype

dtype('float64')

In [40]:
np_array61 = np_array6.astype(int)
np_array61.dtype

dtype('int64')

---
<a id=2></a>
[Topへ](#0)

---
## 2.Numpyの関数で数列を作成

* np.arange(start, stop, step) : 等差数列
* np.linspace(start, stop, size) : 範囲と生成数から作成
---

np.arange(start, stop, step) : 等差数列（正の値のみ）

In [42]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

np.linspace(start, stop, size) : 範囲と生成数から作成

In [44]:
np.arange(0 , 8 , 2)

array([0, 2, 4, 6])

In [46]:
np.arange(-5, 5 , 2)

array([-5, -3, -1,  1,  3])

In [48]:
np.linspace(0, 10)
# デフォルトは50個刻み

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [49]:
np.linspace(0, 5, 10)
# stopを含む

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [50]:
np.linspace(0, 5, 10, endpoint=False)
# stopを含まない

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

---
<a id=3></a>
[Topへ](#0)

---
## 3.Randomモジュールによる乱数Arrayの作成

* np.random.randint(low, high, size): 整数
* 乱数シード
* np.random.rand(size) : 0以上1未満 
* np.random.randn(size) : 平均0、標準偏差1、正規分布に近づく数列  
* np.random.normal(average, satandard_deviation, size) : 平均と標準偏差を指定、正規分布に近づく数列
* np.random.uniform(low, high, size) : 範囲と生成数を指定
* np.random.choice(array, size) : Listの値をランダムに選択
---

np.random.randint(low, high, size): 整数

In [54]:
np.random.randint(10, 20)


13

In [56]:
np.random.randint(10, 20, 5)

array([12, 17, 14, 12, 16])

In [58]:
np.random.randint(10, 20, (3,4 ))

array([[16, 18, 19, 19],
       [17, 13, 13, 13],
       [18, 12, 14, 13]])

In [59]:
np.random.randint(10, 20, (3,4, 3))

array([[[12, 15, 13],
        [12, 18, 10],
        [12, 16, 19],
        [14, 15, 12]],

       [[12, 13, 18],
        [10, 17, 16],
        [13, 18, 18],
        [12, 10, 12]],

       [[11, 14, 18],
        [18, 15, 14],
        [11, 12, 14],
        [16, 11, 19]]])

乱数シード

In [64]:
np.random.seed(17)
np.random.randint(10, 20)

11

In [65]:
np.random.randint(1, 100)

16

np.random.rand(size) : 0以上1未満

In [68]:
np.random.rand(10)

array([0.57041736, 0.03431319, 0.21551321, 0.48756902, 0.27270586,
       0.11906343, 0.29963408, 0.37785406, 0.0011239 , 0.47763181])

np.random.randn(size) : 平均0、標準偏差1、正規分布に近づく数列  

    ※ 分散    ：「各数値の平均との差」を平方（2乗）した値の平均（平方するのはプラスの値で測るため）  
    ※ 標準偏差：平均からのばらつき具合を示す指標。分散の正の平方根  
    ※ 正規分布：平均値の度数を中心に、正負の値の度数が同程度に広がる分布      

In [80]:
np.random.normal(50, 1, 10)

array([48.39732572, 50.6815287 , 51.69023229, 50.83105896, 49.52525403,
       50.95854742, 50.19213224, 48.65422259, 51.25476513, 49.1815836 ])

 np.random.normal(average, satandard_deviation, size) : 平均と標準偏差を指定、正規分布に近づく数列

In [82]:
np.random.normal(50, 1, (2, 5))

array([[50.17738684, 49.12058768, 48.0979914 , 51.03297026, 50.58550965],
       [49.51365092, 49.28801866, 51.06090565, 50.39333933, 50.74605735]])

In [2]:
# pip3 install matplotlib
import matplotlib.pyplot as plt

plt.hist(np.random.normal(100, 20, 1000), bins=30)
plt.show()

SyntaxError: invalid syntax (2035245832.py, line 1)

np.random.uniform(low, high, size) : 範囲と生成数を指定,連続一様分布に近づく

In [73]:
np.random.uniform(2, 8 , 1000)

array([2.67258627, 2.782598  , 4.582542  , 6.97893556, 4.30320679,
       2.03372101, 5.22485274, 7.15240084, 6.0772207 , 6.28119669,
       5.61888688, 7.66126126, 5.81734116, 7.77265801, 2.03169537,
       7.09112568, 2.0691039 , 7.77038784, 3.8041209 , 6.29000418,
       4.19280095, 4.66400005, 6.02523065, 4.0828897 , 2.50295533,
       6.90723749, 6.39665021, 5.97116517, 5.4614128 , 5.62867207,
       4.81137179, 2.26746573, 6.77383687, 5.67034299, 4.08120276,
       5.22503859, 5.78888785, 6.03759928, 6.59697532, 3.14614104,
       7.90278907, 5.68951464, 6.65206845, 2.38858481, 3.85753446,
       7.65418826, 7.671736  , 2.39291352, 3.65700602, 3.49350898,
       4.17280871, 6.73127425, 4.99487302, 7.99919791, 7.59494518,
       7.62809718, 2.5708692 , 3.87895933, 2.65514444, 6.55629732,
       5.30592841, 4.71530797, 2.66585045, 3.48113787, 4.93512065,
       3.91640578, 2.89260903, 4.10944204, 2.98499725, 2.8748234 ,
       2.9760332 , 2.05708859, 4.63717661, 7.41821933, 5.17395

np.random.choice(array, size) : Listの値をランダムに選択

In [77]:
l = [16, 87, 233, 1000]
np.random.choice(l, 5)

array([  16,   16,  233, 1000,   87])

In [78]:
l = [16, 87, 233, 1000]
np.random.choice(l, (2,3 ))

array([[ 233,   87, 1000],
       [  87, 1000,   87]])

---
<a id=4></a>
[Topへ](#0)

---
## 4.Numpy ndarrayの次元、形状、サイズ

* 次元
* 形状
* サイズ（要素数）
* 形状の変換 
---

In [4]:
np_arr = np.random.rand(2, 3, 4)
np_arr

array([[[0.30493188, 0.52080114, 0.62446151, 0.17526196],
        [0.23781386, 0.44358674, 0.68204518, 0.69925502],
        [0.75530583, 0.07050276, 0.65482883, 0.02792994]],

       [[0.14352775, 0.21678549, 0.09796247, 0.13288329],
        [0.76261079, 0.07818662, 0.51977871, 0.5320355 ],
        [0.24965989, 0.81448395, 0.31548675, 0.61564305]]])

次元

In [6]:
np_arr.ndim

3

形状

In [8]:
np_arr.shape



(2, 3, 4)

In [14]:
np.array([1, 2, 3]).shape

(3,)

In [13]:
np.array([[1,2,3],[4,5,6]]).shape

(2, 3)

サイズ（要素数）

In [16]:
np_arr.size

24

In [17]:
np.array([[1,2,3],[4,5,6]]).size

6

形状の変換

In [21]:
np_arr.reshape(4, 6)

array([[0.30493188, 0.52080114, 0.62446151, 0.17526196, 0.23781386,
        0.44358674],
       [0.68204518, 0.69925502, 0.75530583, 0.07050276, 0.65482883,
        0.02792994],
       [0.14352775, 0.21678549, 0.09796247, 0.13288329, 0.76261079,
        0.07818662],
       [0.51977871, 0.5320355 , 0.24965989, 0.81448395, 0.31548675,
        0.61564305]])

---
<a id=5></a>
[Topへ](#0)

---
## 5.Numpy ndarrayの演算例

In [22]:
np_arr *1000

array([[[304.93188349, 520.80114005, 624.46151251, 175.26196427],
        [237.81385884, 443.58674149, 682.04517803, 699.25501979],
        [755.30583059,  70.50275727, 654.82883074,  27.92994403]],

       [[143.52774878, 216.78549418,  97.96246819, 132.88329479],
        [762.61078886,  78.18662233, 519.77870793, 532.03549592],
        [249.65989177, 814.48394653, 315.48675005, 615.64305131]]])

---
[Topへ](#0)

---
## 以上
    
---