---
# 1. Numpy Exercise
---

Exercise_1 : Numpyライブラリを np というエイリアスでインポートしてください

In [1]:
import numpy as np

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>import numpy as np</code>
</details>

Exercise_2 :  [1, 3, 5, ..., 21, 23] の連続する値を持つ1次元のNumpy Array（変数名 arr1）を作成してください

In [5]:
arr1 = np.arange(1, 24, 2)
arr1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1 = np.arange(1, 24, 2)</code>
</details>

Exercise_3 : [0., 0.5, 1, ..., 5.5, 6.] （要素数は13）の連続する値を持つ1次元のNumpy Array（変数名 arr2）を作成してください

In [9]:
arr2 = np.arange(0, 6.1, 0.5)
arr2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ])

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr2 = np.linspace(0, 6, 13)</code><br>
    <code>np.arange(0, 6.1, 0.5)</code>などでも可
</details>

Exercise_4 : arr1 を3行4列の配列に変換してください(arr1_reshaped)

In [10]:
arr1_reshaped = arr1.reshape(3, 4)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1_reshaped = arr1.reshape(3, 4)</code>
</details>

In [11]:
# 実行して表示
arr1_reshaped

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

Exercise_5: arr1 を2次元で1列の配列に変換してください(arr1_1col)

In [12]:
arr1_1col = arr1.reshape(-1, 1)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1_1col = arr1.reshape(-1, 1)</code>
</details>

In [13]:
# 実行して表示
arr1_1col

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19],
       [21],
       [23]])

Exercise_6 : arr1 を1次元の配列に変換してください(arr1_1dim)。ただし、arr1を扱っていく一方で、arr1_1dimの値の更新を行っていくことを前提とします。（もとのarr1のデータが変更されない手法を用いる）

In [18]:
# arr1_1dim = arr1.reshape(-1)
arr1_1dim = arr1.flatten()


<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1_1dim = arr1.flatten()</code>
    <p>※ ravel()の場合はarr1_1dimを更新するとarr1も更新されてしまうため</p>
</details>

In [19]:
# 実行して表示
arr1_1dim

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

Exercise_7 : arr1_reshaped の次元数とその形状を確認してください

In [21]:
# 次元
arr1_reshaped.ndim

2

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1_reshaped.ndim</code>
</details>

In [22]:
# 形状
arr1_reshaped.shape

(3, 4)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1_reshaped.shape</code>
</details>

Exercise_8: Numpy の random モジュールを使い、0以上1未満の乱数を5つ持つ一次元の配列を作成してください（arr3）

In [23]:
arr3 = np.random.rand(5)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr3 = np.random.rand(5)</code>
</details>

In [24]:
# 実行して表示
arr3

array([0.12770855, 0.12126293, 0.28800138, 0.08534586, 0.80189349])

Exercise_9: 0以上1未満の乱数を持つ2行6列の配列を作成してください（arr4）

In [25]:
arr4 = np.random.rand(2, 6)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr4 = np.random.rand(2, 6)</code>
</details>

In [26]:
# 実行して表示
arr4

array([[0.00205008, 0.58249094, 0.94122728, 0.77840679, 0.64261688,
        0.89476576],
       [0.11670502, 0.79596063, 0.63837197, 0.14376525, 0.6726475 ,
        0.87251296]])

Exercise_10 : 平均が 0、標準偏差が 1 で、正規分布に従う値を持つ3行4列の配列を作成してください （arr5）

In [30]:
# arr5 = np.random.normal(0, 1, (3,4))
arr5 = np.random.randn(3, 4)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr5 = np.random.randn(3, 4)</code>
</details>

In [31]:
# 実行して表示
arr5

array([[-1.93939663,  0.26387092,  0.92505159, -2.49165505],
       [-0.30119049,  0.82500905,  0.94367796,  1.34486845],
       [ 0.14989445,  1.44919904, -1.18556739,  1.31116402]])

Exercise_11 : arr5 の全要素での、最大値、最小値、平均を確認してください（max_arr5, min_arr5, mean_arr5）

In [34]:
max_arr5 = arr5.max()
min_arr5 = arr5.min()
mean_arr5 = arr5.mean()
print(f'max : {max_arr5}, min : {min_arr5}, mean : {mean_arr5}')
# 各行ではなく、全体の最大などを取得していることに注意

max : 1.4491990442977, min : -2.491655048961709, mean : 0.10791049390564356


<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>max_arr5 = arr5.max()</code><br>
    <code>min_arr5 = arr5.min()</code><br>
    <code>mean_arr5 = arr5.mean()</code>
</details>

Exercise_12: 平均が 100、標準偏差が 10 で、正規分布に従う値を持つ3行4列の配列を作成してください （arr6）

In [35]:
arr6 = np.random.normal(100, 10, (3, 4))

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr6 = np.random.normal(100, 10, (3, 4))</code>
</details>

In [36]:
# 実行して表示
arr6

array([[ 97.01951866,  85.51936831,  98.1046215 ,  99.5796796 ],
       [ 92.97747529,  96.78978069,  95.63190595,  81.34955501],
       [100.2203885 ,  89.93431629, 109.33369978,  94.84751372]])

Exercise_13 : 10 以上 30 未満の値を持つ連続一様分布の3行4列の配列を作成してください （arr7）。また要素全体の平均値が20付近にあることを平均値を求めることで確認してください。

In [39]:
arr7 = np.random.uniform(10, 30, (3, 4))

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr7 = np.random.uniform(10, 30, (3, 4))</code>
</details>

In [40]:
# 実行して表示
arr7

array([[20.65383436, 22.55222341, 26.34167018, 22.31830238],
       [16.96814688, 24.92403646, 17.5856903 , 25.10587233],
       [27.10987414, 28.32345988, 21.44473692, 19.41864033]])

In [41]:
# 平均値を求める
arr7.mean()

# 20前後の値ならばOK

22.72887396431531

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr7.mean()</code>
</details>

Exercise_14 : arr7 の数値をすべて小数第4位で四捨五入した小数3桁の値に変換してください(arr7_3decimal)

In [42]:
arr7_3decimal = np.round(arr7, 3)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1_3decimal = np.round(arr7, 3)</code>
</details>

In [43]:
# 実行して表示
arr7_3decimal

array([[20.654, 22.552, 26.342, 22.318],
       [16.968, 24.924, 17.586, 25.106],
       [27.11 , 28.323, 21.445, 19.419]])

Exercise_15: リスト lis の文字をランダムに10個持つ1次元の配列を作成し（arr8）、データタイプを object に変更してください

In [52]:
# リストを作成
lis = list('GOOD!')   # ['G', 'O', 'O', 'D', '!']
arr8 = np.random.choice(lis, 10)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr8 = np.random.choice(lis, 10)</code>
</details>

In [53]:
# 実行して表示
arr8

array(['G', 'D', '!', 'D', 'D', 'G', 'O', 'D', 'D', 'D'], dtype='<U1')

In [55]:
# データタイプを変更
arr8 = arr8.astype(object)
arr8.dtype

dtype('O')

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr8 = arr8.astype(object)</code>
</details>

In [56]:
# 実行して表示
arr8

array(['G', 'D', '!', 'D', 'D', 'G', 'O', 'D', 'D', 'D'], dtype=object)

Exercise_16 : 次のarr9のデータタイプが 'int32' であることを確認し、その後データタイプを 'float' に変更してください

In [57]:
# dtypeの確認
arr9 = np.array([1, 3, 5, 7, 9]) 
arr9.dtype

dtype('int64')

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr9.dtype</code>
</details>

In [59]:
# floatに変更
arr9 = arr9.astype(float)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr9.astype(float)</code><br>
</details>

In [60]:
# 実行して表示
arr9

array([1., 3., 5., 7., 9.])

Exercise_17 : 配列arr10の分散と標準偏差を「計算して」求めてください。また、メソッドを用いてその値が正しいことを確認してください。

In [61]:
# 実行して表示
np.random.seed(17)
arr10 = np.random.randint(0, 10, 5)
arr10

array([1, 6, 6, 9, 0])

In [62]:
# 実行して表示
mean = arr10.mean()
mean

4.4

In [64]:
total = 0
for i in arr10:
    total += i
total

22

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>total += (i - mean)**2</code><br>
</details>

In [65]:
variance = total / len(arr10)
# 実行して表示
variance

4.4

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>variance = total / len(arr10)</code><br>
</details>

In [66]:
standard_deviation = np.sqrt(arr10)
# 実行して表示
standard_deviation

array([1.        , 2.44948974, 2.44948974, 3.        , 0.        ])

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>standard_deviation = np.sqrt(variance)</code><br>
</details>

In [67]:
# メソッドを使って分散を求める
arr10.var()

11.440000000000001

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr10.var()</code><br>
</details>

In [68]:
# メソッドを使って標準偏差を求める
arr10.std()

3.3823069050575527

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr10.std()</code><br>
</details>

## 以上